### PR TITLE
Update 'collapsible-panel-header' locator

### PR DESCRIPTION
**Pull request by YuriChupyrkin**
Fix of selenium tests

### CODE REVIEW

**Comment by DimaDK24** [comment]
@YuriChupyrkin, please rebase on the updated branch, or maybe I should just cherry-pick your commit to put it in [my PR](https://github.com/google/ggrc-core/pull/9495)?

**Comment by YuriChupyrkin** [comment]
@DimaDK24 , please cherry-pick commit :)

**Comment by DimaDK24** [comment]
@YuriChupyrkin, done

**Comment by DimaDK24** [comment]
PR closed, cause commit with the fix is cherry-picked in the [original PR](https://github.com/google/ggrc-core/pull/9495).

**Pull request closed without merging**
